export const STORE_FETCHED_PING = 'STORE_FETCHED_PING'
export const PING_LOADED = 'PING_LOADED'

export const STORE_FETCHED_FILES = 'STORE_FETCHED_FILES'
export const FILES_LOADED = 'FILES_LOADED'
export const LOAD_PREVIEW = 'LOAD_PREVIEW'
export const UNLOAD_PREVIEW = 'UNLOAD_PREVIEW'

export const STORE_FETCHED_USER = 'STORE_FETCHED_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const INCREMENT_LOADING_PROGRESS = 'INCREMENT_LOADING_PROGRESS'
export const RESET_LOADING_PROGRESS = 'RESET_LOADING_PROGRESS'
